version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/aws-nano-dynamo-api-gateway'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/aws-minimal-dynamo-api-gateway'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/aws-nano-express-dynamo-api'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/aws-minimal-express-dynamo-api'
    schedule:
      interval: 'weekly'
